title: Siddhartha Anand # your name (or website title) here
logo: "/images/coffeemug.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A passionate developer looking for great opportunities.
  <br><br>
  <a href="https://www.linkedin.com/in/siddharthaanand/">LinkedIn</a>
  <br><br>
  <a href="https://siddharthaanand.github.io/pdf/SiddharthaCV.pdf">Resume</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
